version: '3.4'

# Visual Studio Code doesn't look at the compose.override.yml file (https://github.com/Microsoft/vscode-docker/issues/379).
# For now, set all debug environment settings here.

services:
  teamassembler.frontend:
    image: amolenk.azurecr.io/teamassembler-frontend
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services_Superhero_Url=http://teamassembler.superheroservice
      - Services_Team_Url=http://teamassembler.teamservice
    depends_on: 
      - teamassembler.superheroservice
      - teamassembler.teamservice

  teamassembler.superheroservice:
    image: amolenk.azurecr.io/teamassembler-superheroservice
    build:
      context: .
      dockerfile: SuperheroService/Dockerfile
    ports:
      - "8080:80"

  teamassembler.teamservice:
    image: amolenk.azurecr.io/teamassembler-teamservice
    build:
      context: .
      dockerfile: TeamService/Dockerfile
    ports:
      - "8081:80"
    volumes:
      - "~/teams:/app/data"