version: '3.4'

# Visual Studio Code doesn't look at the compose.override.yml file (https://github.com/Microsoft/vscode-docker/issues/379).
# For now, set all debug environment settings here.

services:
  teamassembler.frontend:
    image: amolenk.azurecr.io/teamassembler-frontend:v1
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services_Superhero_Url=http://teamassembler.superheroservice
      - Services_Team_Url=http://teamassembler.teamservice

  teamassembler.superheroservice:
    image: amolenk.azurecr.io/teamassembler-superheroservice:v1
    build:
      context: .
      dockerfile: SuperheroService/Dockerfile

  teamassembler.teamservice:
    image: amolenk.azurecr.io/teamassembler-teamservice:v1
    build:
      context: .
      dockerfile: TeamService/Dockerfile
    volumes:
      - "~/teams:/app/data"